CREATE TABLE  user(
	id VARCHAR(10) PRIMARY KEY  COMMENT '用户id',
	username VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
	password VARCHAR(20) NOT NULL DEFAULT '' COMMENT '密码',
	age TINYINT NOT NULL DEFAULT 0 COMMENT '年龄'
) CHARACTER SET utf8 COMMENT '用户表';

INSERT INTO user VALUES('111','admin','123456',18);
INSERT INTO user VALUES('222','root','123',19);
