package me.xueyao.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-11-06T19:07:01.419+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://service.cxf.xueyao.me/", name = "MobileAddressService")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileAddressService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAddressByMobileNo", targetNamespace = "http://service.cxf.xueyao.me/", className = "me.xueyao.cxf.client.GetAddressByMobileNo")
    @WebMethod
    @ResponseWrapper(localName = "getAddressByMobileNoResponse", targetNamespace = "http://service.cxf.xueyao.me/", className = "me.xueyao.cxf.client.GetAddressByMobileNoResponse")
    public String getAddressByMobileNo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
