CREATE TABLE IF NOT EXISTS user(
	id VARCHAR(20) AUTO_INCREMENT COMMENT '用户id',
	name VARCHAR(20) COMMENT '用户名',
	age INT COMMENT '年龄',
	password VARCHAR(20) NOT NULL COMMENT '密码',
	PRIMARY KEY (id)
)CHARACTER SET utf8 COMMENT '用户表';